name: Update GeoLite2 database
on:
  workflow_dispatch:
jobs:
  update-geolite2-if-changed:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: |
          echo 'success'
